const MAIN_URL = 'http://localhost:8000/';
export const PRODUCT_URL = MAIN_URL + 'api/products';
export const CUSTOMER_URL = MAIN_URL + 'api/customers';

/*product actions*/
export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const OPEN_PRODUCT_MODAL = 'OPEN_PRODUCT_MODAL';
export const CLOSE_PRODUCT_MODAL = 'CLOSE_PRODUCT_MODAL';
export const SUBMIT_PRODUCT_MODAL = 'SUBMIT_PRODUCT_MODAL';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const DELETE_PRODUCT_MODAL_OPEN = 'DELETE_PRODUCT_MODAL_OPEN';
export const DELETE_PRODUCT_MODAL_CLOSE = 'DELETE_PRODUCT_MODAL_CLOSE';
/*product actions*/
/*customer actions*/
export const REQUEST_CUSTOMERS = 'REQUEST_CUSTOMERS';
export const RECEIVE_CUSTOMERS = 'RECEIVE_CUSTOMERS';
export const OPEN_CUSTOMER_MODAL = 'OPEN_CUSTOMER_MODAL';
export const CLOSE_CUSTOMER_MODAL = 'CLOSE_CUSTOMER_MODAL';
export const SUBMIT_CUSTOMER_MODAL = 'SUBMIT_CUSTOMER_MODAL';
export const SELECT_CUSTOMER = 'SELECT_CUSTOMER';
export const DELETE_CUSTOMER_MODAL_OPEN = 'DELETE_CUSTOMER_MODAL_OPEN';
export const DELETE_CUSTOMER_MODAL_CLOSE = 'DELETE_CUSTOMER_MODAL_CLOSE';

/*customer actions*/
